### ISSUE TITLE
Strings.singulatePt está deixando lowerCase

### ISSUE THREAD

**Issue by douglasfelipebs** [Acelera/af-helpers#18]
Ao utilizar o helper Strings.singulatePt para tornar uma string singular, o mesmo está me retornando a string toLowerCase, e em certos casos eu gostaria de manter o Case como estava.

**Comment by maviniciuus** [comment]
Teria que preservar o case, provavelmente vou precisar adicionar várias combinações de exceções....

**Comment by maviniciuus** [comment]
Fiz a correção se o problema persistir fique a vontade pra reabrir!
